
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const AppLayout = lazy(() => import("./pages/AppLayout.tsx"));
const Discover = lazy(() => import("./pages/Discover.tsx"));
const ProfileCompletion = lazy(() => import("./pages/ProfileCompletion.tsx"));
const ProfileDisplay = lazy(() => import("./pages/ProfileDisplay.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/app-layout", element: <UserGuard><AppLayout /></UserGuard>},
	{ path: "/applayout", element: <UserGuard><AppLayout /></UserGuard>},
	{ path: "/discover", element: <UserGuard><Discover /></UserGuard>},
	{ path: "/profile-completion", element: <UserGuard><ProfileCompletion /></UserGuard>},
	{ path: "/profilecompletion", element: <UserGuard><ProfileCompletion /></UserGuard>},
	{ path: "/profile-display", element: <UserGuard><ProfileDisplay /></UserGuard>},
	{ path: "/profiledisplay", element: <UserGuard><ProfileDisplay /></UserGuard>},

];
