
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const VideoLibraryPage = lazy(() => import("./pages/VideoLibraryPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/video-library-page", element: <VideoLibraryPage />},
	{ path: "/videolibrarypage", element: <VideoLibraryPage />},

];
